// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Device hardware profile from native.
class NativeDeviceProfile {
  NativeDeviceProfile({
    required this.totalRamMB,
    required this.availableRamMB,
    this.gpuName,
    required this.vulkanSupported,
    required this.cpuCores,
    required this.cpuArchitecture,
    required this.sdkVersion,
    required this.deviceModel,
    required this.manufacturer,
  });

  int totalRamMB;

  int availableRamMB;

  String? gpuName;

  bool vulkanSupported;

  int cpuCores;

  String cpuArchitecture;

  int sdkVersion;

  String deviceModel;

  String manufacturer;

  List<Object?> _toList() {
    return <Object?>[
      totalRamMB,
      availableRamMB,
      gpuName,
      vulkanSupported,
      cpuCores,
      cpuArchitecture,
      sdkVersion,
      deviceModel,
      manufacturer,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeDeviceProfile decode(Object result) {
    result as List<Object?>;
    return NativeDeviceProfile(
      totalRamMB: result[0]! as int,
      availableRamMB: result[1]! as int,
      gpuName: result[2] as String?,
      vulkanSupported: result[3]! as bool,
      cpuCores: result[4]! as int,
      cpuArchitecture: result[5]! as String,
      sdkVersion: result[6]! as int,
      deviceModel: result[7]! as String,
      manufacturer: result[8]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDeviceProfile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Battery state from native.
class NativeBatteryState {
  NativeBatteryState({
    required this.level,
    required this.isCharging,
  });

  double level;

  bool isCharging;

  List<Object?> _toList() {
    return <Object?>[
      level,
      isCharging,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeBatteryState decode(Object result) {
    result as List<Object?>;
    return NativeBatteryState(
      level: result[0]! as double,
      isCharging: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeBatteryState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeDeviceProfile) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeBatteryState) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativeDeviceProfile.decode(readValue(buffer)!);
      case 130: 
        return NativeBatteryState.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter → Native: Device profiling.
class DeviceHostApi {
  /// Constructor for [DeviceHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Get full device hardware profile.
  Future<NativeDeviceProfile> getDeviceProfile() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.DeviceHostApi.getDeviceProfile$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeDeviceProfile?)!;
    }
  }

  /// Get current battery state.
  Future<NativeBatteryState> getBatteryState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.DeviceHostApi.getBatteryState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeBatteryState?)!;
    }
  }

  /// Get available storage in MB.
  Future<int> getAvailableStorageMB() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.DeviceHostApi.getAvailableStorageMB$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }
}

/// Native → Flutter: Device state change callbacks.
abstract class DeviceFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when thermal state changes.
  void onThermalStateChanged(int thermalState);

  /// Called when battery state changes significantly.
  void onBatteryStateChanged(double level, bool isCharging);

  static void setUp(DeviceFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.babymomo.DeviceFlutterApi.onThermalStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.babymomo.DeviceFlutterApi.onThermalStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_thermalState = (args[0] as int?);
          assert(arg_thermalState != null,
              'Argument for dev.flutter.pigeon.babymomo.DeviceFlutterApi.onThermalStateChanged was null, expected non-null int.');
          try {
            api.onThermalStateChanged(arg_thermalState!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.babymomo.DeviceFlutterApi.onBatteryStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.babymomo.DeviceFlutterApi.onBatteryStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_level = (args[0] as double?);
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.babymomo.DeviceFlutterApi.onBatteryStateChanged was null, expected non-null double.');
          final bool? arg_isCharging = (args[1] as bool?);
          assert(arg_isCharging != null,
              'Argument for dev.flutter.pigeon.babymomo.DeviceFlutterApi.onBatteryStateChanged was null, expected non-null bool.');
          try {
            api.onBatteryStateChanged(arg_level!, arg_isCharging!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
