// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Model loading request sent from Flutter to native.
class NativeModelRequest {
  NativeModelRequest({
    required this.modelPath,
    required this.contextLength,
    required this.threadCount,
    required this.useGPU,
  });

  String modelPath;

  int contextLength;

  int threadCount;

  bool useGPU;

  List<Object?> _toList() {
    return <Object?>[
      modelPath,
      contextLength,
      threadCount,
      useGPU,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeModelRequest decode(Object result) {
    result as List<Object?>;
    return NativeModelRequest(
      modelPath: result[0]! as String,
      contextLength: result[1]! as int,
      threadCount: result[2]! as int,
      useGPU: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeModelRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Inference request sent from Flutter to native.
class NativeInferenceRequest {
  NativeInferenceRequest({
    required this.requestId,
    required this.prompt,
    this.systemPrompt,
    required this.temperature,
    required this.topP,
    required this.maxTokens,
  });

  String requestId;

  String prompt;

  String? systemPrompt;

  double temperature;

  double topP;

  int maxTokens;

  List<Object?> _toList() {
    return <Object?>[
      requestId,
      prompt,
      systemPrompt,
      temperature,
      topP,
      maxTokens,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeInferenceRequest decode(Object result) {
    result as List<Object?>;
    return NativeInferenceRequest(
      requestId: result[0]! as String,
      prompt: result[1]! as String,
      systemPrompt: result[2] as String?,
      temperature: result[3]! as double,
      topP: result[4]! as double,
      maxTokens: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeInferenceRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Model info returned from native.
class NativeModelInfo {
  NativeModelInfo({
    required this.modelPath,
    required this.parameterCount,
    required this.contextLength,
    required this.quantization,
    required this.isLoaded,
  });

  String modelPath;

  int parameterCount;

  int contextLength;

  String quantization;

  bool isLoaded;

  List<Object?> _toList() {
    return <Object?>[
      modelPath,
      parameterCount,
      contextLength,
      quantization,
      isLoaded,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeModelInfo decode(Object result) {
    result as List<Object?>;
    return NativeModelInfo(
      modelPath: result[0]! as String,
      parameterCount: result[1]! as int,
      contextLength: result[2]! as int,
      quantization: result[3]! as String,
      isLoaded: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeModelInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeModelRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeInferenceRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativeModelInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativeModelRequest.decode(readValue(buffer)!);
      case 130: 
        return NativeInferenceRequest.decode(readValue(buffer)!);
      case 131: 
        return NativeModelInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter → Native: Inference operations.
class InferenceHostApi {
  /// Constructor for [InferenceHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  InferenceHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Load a model into memory.
  Future<bool> loadModel(NativeModelRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.InferenceHostApi.loadModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Unload the currently loaded model.
  Future<void> unloadModel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.InferenceHostApi.unloadModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start inference (tokens streamed back via [InferenceFlutterApi]).
  Future<void> startInference(NativeInferenceRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.InferenceHostApi.startInference$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Cancel the currently running inference.
  Future<void> cancelInference(String requestId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.InferenceHostApi.cancelInference$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get info about the currently loaded model.
  Future<NativeModelInfo?> getModelInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.InferenceHostApi.getModelInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as NativeModelInfo?);
    }
  }

  /// Check if a model is currently loaded.
  Future<bool> isModelLoaded() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.InferenceHostApi.isModelLoaded$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

/// Native → Flutter: Token streaming callbacks.
abstract class InferenceFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called for each generated token.
  void onToken(String requestId, String token);

  /// Called when inference completes.
  void onComplete(String requestId, int totalTokens, double tokensPerSecond);

  /// Called when inference encounters an error.
  void onError(String requestId, String errorMessage);

  static void setUp(InferenceFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.babymomo.InferenceFlutterApi.onToken$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onToken was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_requestId = (args[0] as String?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onToken was null, expected non-null String.');
          final String? arg_token = (args[1] as String?);
          assert(arg_token != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onToken was null, expected non-null String.');
          try {
            api.onToken(arg_requestId!, arg_token!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.babymomo.InferenceFlutterApi.onComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_requestId = (args[0] as String?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onComplete was null, expected non-null String.');
          final int? arg_totalTokens = (args[1] as int?);
          assert(arg_totalTokens != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onComplete was null, expected non-null int.');
          final double? arg_tokensPerSecond = (args[2] as double?);
          assert(arg_tokensPerSecond != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onComplete was null, expected non-null double.');
          try {
            api.onComplete(arg_requestId!, arg_totalTokens!, arg_tokensPerSecond!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.babymomo.InferenceFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_requestId = (args[0] as String?);
          assert(arg_requestId != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onError was null, expected non-null String.');
          final String? arg_errorMessage = (args[1] as String?);
          assert(arg_errorMessage != null,
              'Argument for dev.flutter.pigeon.babymomo.InferenceFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_requestId!, arg_errorMessage!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
