import 'dart:async';
import 'package:get/get.dart';
import 'package:hive_ce_flutter/hive_flutter.dart';
import 'storage_service.dart';
import '../security/security_engine.dart';

/// MOMO Core — Hive CE storage implementation.
///
/// Implements [StorageService] using Hive CE for local-first persistence.
/// Each domain gets its own box for isolation and performance.
class HiveStorageImpl extends GetxService implements StorageService {
  final Map<String, Box> _openBoxes = {};

  @override
  Future<void> init() async {
    await Hive.initFlutter();

    // Register type adapters here as models are created.
    // TypeAdapters will be generated by hive_ce_generator.

    // Pre-open frequently used boxes
    await _ensureBoxOpen(StorageBoxes.settings);
    await _ensureBoxOpen(StorageBoxes.sessions);
  }

  Future<Box<dynamic>> _ensureBoxOpen(String boxName) async {
    if (_openBoxes.containsKey(boxName)) {
      return _openBoxes[boxName]!;
    }

    HiveCipher? encryptionCipher;
    // Apply dynamic Hive box encryption on sessions and memory boxes (contains personal user data)
    if (boxName == StorageBoxes.sessions || boxName == StorageBoxes.memory) {
      try {
        final securityEngine = Get.find<SecurityEngine>();
        final encryptionKey = await securityEngine.getEncryptionKey();
        encryptionCipher = HiveAesCipher(encryptionKey);
      } catch (e) {
        // Strict Secure Fail: propagate the exception immediately to block app launch and compromise
        rethrow;
      }
    }

    final box = await Hive.openBox(boxName, encryptionCipher: encryptionCipher);
    _openBoxes[boxName] = box;
    return box;
  }

  @override
  Future<T?> get<T>(String box, String key) async {
    final b = await _ensureBoxOpen(box);
    return b.get(key) as T?;
  }

  @override
  Future<void> put<T>(String box, String key, T value) async {
    final b = await _ensureBoxOpen(box);
    await b.put(key, value);
  }

  @override
  Future<void> delete(String box, String key) async {
    final b = await _ensureBoxOpen(box);
    await b.delete(key);
  }

  @override
  Future<List<T>> getAll<T>(String box) async {
    final b = await _ensureBoxOpen(box);
    return b.values.cast<T>().toList();
  }

  @override
  Future<void> clearBox(String box) async {
    final b = await _ensureBoxOpen(box);
    await b.clear();
  }

  @override
  Future<bool> containsKey(String box, String key) async {
    final b = await _ensureBoxOpen(box);
    return b.containsKey(key);
  }

  @override
  Stream<T?> watch<T>(String box, String key) {
    final controller = StreamController<T?>();

    _ensureBoxOpen(box).then((b) {
      final subscription = b.watch(key: key).listen((event) {
        controller.add(event.value as T?);
      });
      controller.onCancel = () => subscription.cancel();
    });

    return controller.stream;
  }

  @override
  Future<void> dispose() async {
    for (final box in _openBoxes.values) {
      await box.close();
    }
    _openBoxes.clear();
  }
}
