// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Image generation request sent from Flutter to native.
class NativeImageRequest {
  NativeImageRequest({
    required this.prompt,
    required this.negativePrompt,
    required this.steps,
    required this.cfgScale,
    required this.width,
    required this.height,
    required this.seed,
  });

  String prompt;

  String negativePrompt;

  int steps;

  double cfgScale;

  int width;

  int height;

  int seed;

  List<Object?> _toList() {
    return <Object?>[
      prompt,
      negativePrompt,
      steps,
      cfgScale,
      width,
      height,
      seed,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeImageRequest decode(Object result) {
    result as List<Object?>;
    return NativeImageRequest(
      prompt: result[0]! as String,
      negativePrompt: result[1]! as String,
      steps: result[2]! as int,
      cfgScale: result[3]! as double,
      width: result[4]! as int,
      height: result[5]! as int,
      seed: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeImageRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Image generation response returned from native.
class NativeImageResponse {
  NativeImageResponse({
    required this.imagePath,
    required this.generationTimeMs,
    required this.success,
    this.errorMessage,
  });

  String imagePath;

  int generationTimeMs;

  bool success;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      imagePath,
      generationTimeMs,
      success,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeImageResponse decode(Object result) {
    result as List<Object?>;
    return NativeImageResponse(
      imagePath: result[0]! as String,
      generationTimeMs: result[1]! as int,
      success: result[2]! as bool,
      errorMessage: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeImageResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeImageRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeImageResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return NativeImageRequest.decode(readValue(buffer)!);
      case 130: 
        return NativeImageResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter → Native: Image Generation operations.
class ImageGenHostApi {
  /// Constructor for [ImageGenHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImageGenHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generate a high-fidelity image based on the prompt.
  Future<NativeImageResponse> generateImage(NativeImageRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.babymomo.ImageGenHostApi.generateImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeImageResponse?)!;
    }
  }
}
