// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.momoai.babymomo.pigeon.imagegen

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ImageGenApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Image generation request sent from Flutter to native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeImageRequest (
  val prompt: String,
  val negativePrompt: String,
  val steps: Long,
  val cfgScale: Double,
  val width: Long,
  val height: Long,
  val seed: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeImageRequest {
      val prompt = pigeonVar_list[0] as String
      val negativePrompt = pigeonVar_list[1] as String
      val steps = pigeonVar_list[2] as Long
      val cfgScale = pigeonVar_list[3] as Double
      val width = pigeonVar_list[4] as Long
      val height = pigeonVar_list[5] as Long
      val seed = pigeonVar_list[6] as Long
      return NativeImageRequest(prompt, negativePrompt, steps, cfgScale, width, height, seed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      prompt,
      negativePrompt,
      steps,
      cfgScale,
      width,
      height,
      seed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeImageRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return ImageGenApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Image generation response returned from native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeImageResponse (
  val imagePath: String,
  val generationTimeMs: Long,
  val success: Boolean,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeImageResponse {
      val imagePath = pigeonVar_list[0] as String
      val generationTimeMs = pigeonVar_list[1] as Long
      val success = pigeonVar_list[2] as Boolean
      val errorMessage = pigeonVar_list[3] as String?
      return NativeImageResponse(imagePath, generationTimeMs, success, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      imagePath,
      generationTimeMs,
      success,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeImageResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return ImageGenApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ImageGenApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeImageRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeImageResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeImageRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeImageResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter → Native: Image Generation operations.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ImageGenHostApi {
  /** Generate a high-fidelity image based on the prompt. */
  fun generateImage(request: NativeImageRequest, callback: (Result<NativeImageResponse>) -> Unit)

  companion object {
    /** The codec used by ImageGenHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ImageGenApiPigeonCodec()
    }
    /** Sets up an instance of `ImageGenHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ImageGenHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.ImageGenHostApi.generateImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeImageRequest
            api.generateImage(requestArg) { result: Result<NativeImageResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ImageGenApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ImageGenApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
