// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.momoai.babymomo.pigeon.security

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SecurityApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Request parameters for native file integrity verification.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeHashRequest (
  val filePath: String,
  val expectedHash: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHashRequest {
      val filePath = pigeonVar_list[0] as String
      val expectedHash = pigeonVar_list[1] as String
      return NativeHashRequest(filePath, expectedHash)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      filePath,
      expectedHash,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeHashRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return SecurityApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Native file hash verification result.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeHashResponse (
  val hash: String,
  val match: Boolean,
  val success: Boolean,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeHashResponse {
      val hash = pigeonVar_list[0] as String
      val match = pigeonVar_list[1] as Boolean
      val success = pigeonVar_list[2] as Boolean
      val errorMessage = pigeonVar_list[3] as String?
      return NativeHashResponse(hash, match, success, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hash,
      match,
      success,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeHashResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return SecurityApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class SecurityApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHashRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeHashResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeHashRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeHashResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter → Native: Security Host API calls.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SecurityHostApi {
  /** Get or create the master AES-wrapped database encryption key from Android Keystore. */
  fun getOrCreateSecureKey(callback: (Result<String>) -> Unit)
  /** Wipes all secure keys and local shared preferences for security reset. */
  fun wipeSecureStorage(callback: (Result<Unit>) -> Unit)
  /** Compute the SHA-256 hash of a file on a background native thread. */
  fun computeAndVerifySHA256(request: NativeHashRequest, callback: (Result<NativeHashResponse>) -> Unit)

  companion object {
    /** The codec used by SecurityHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SecurityApiPigeonCodec()
    }
    /** Sets up an instance of `SecurityHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SecurityHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.SecurityHostApi.getOrCreateSecureKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getOrCreateSecureKey{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SecurityApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SecurityApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.SecurityHostApi.wipeSecureStorage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.wipeSecureStorage{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SecurityApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(SecurityApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.SecurityHostApi.computeAndVerifySHA256$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeHashRequest
            api.computeAndVerifySHA256(requestArg) { result: Result<NativeHashResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SecurityApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SecurityApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native → Flutter: Hashing progress callbacks.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class SecurityFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SecurityFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      SecurityApiPigeonCodec()
    }
  }
  /** Streamed progress callback for background file hashing. */
  fun onHashProgress(filePathArg: String, progressArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.babymomo.SecurityFlutterApi.onHashProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(filePathArg, progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(SecurityApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
