// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.momoai.babymomo.pigeon.device

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DeviceApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Device hardware profile from native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeDeviceProfile (
  val totalRamMB: Long,
  val availableRamMB: Long,
  val gpuName: String? = null,
  val vulkanSupported: Boolean,
  val cpuCores: Long,
  val cpuArchitecture: String,
  val sdkVersion: Long,
  val deviceModel: String,
  val manufacturer: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeDeviceProfile {
      val totalRamMB = pigeonVar_list[0] as Long
      val availableRamMB = pigeonVar_list[1] as Long
      val gpuName = pigeonVar_list[2] as String?
      val vulkanSupported = pigeonVar_list[3] as Boolean
      val cpuCores = pigeonVar_list[4] as Long
      val cpuArchitecture = pigeonVar_list[5] as String
      val sdkVersion = pigeonVar_list[6] as Long
      val deviceModel = pigeonVar_list[7] as String
      val manufacturer = pigeonVar_list[8] as String
      return NativeDeviceProfile(totalRamMB, availableRamMB, gpuName, vulkanSupported, cpuCores, cpuArchitecture, sdkVersion, deviceModel, manufacturer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalRamMB,
      availableRamMB,
      gpuName,
      vulkanSupported,
      cpuCores,
      cpuArchitecture,
      sdkVersion,
      deviceModel,
      manufacturer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeDeviceProfile) {
      return false
    }
    if (this === other) {
      return true
    }
    return DeviceApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Battery state from native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeBatteryState (
  val level: Double,
  val isCharging: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeBatteryState {
      val level = pigeonVar_list[0] as Double
      val isCharging = pigeonVar_list[1] as Boolean
      return NativeBatteryState(level, isCharging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      isCharging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeBatteryState) {
      return false
    }
    if (this === other) {
      return true
    }
    return DeviceApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class DeviceApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeDeviceProfile.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeBatteryState.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeDeviceProfile -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeBatteryState -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter → Native: Device profiling.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DeviceHostApi {
  /** Get full device hardware profile. */
  fun getDeviceProfile(callback: (Result<NativeDeviceProfile>) -> Unit)
  /** Get current battery state. */
  fun getBatteryState(callback: (Result<NativeBatteryState>) -> Unit)
  /** Get available storage in MB. */
  fun getAvailableStorageMB(callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by DeviceHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceApiPigeonCodec()
    }
    /** Sets up an instance of `DeviceHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.DeviceHostApi.getDeviceProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceProfile{ result: Result<NativeDeviceProfile> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DeviceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DeviceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.DeviceHostApi.getBatteryState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBatteryState{ result: Result<NativeBatteryState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DeviceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DeviceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.DeviceHostApi.getAvailableStorageMB$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAvailableStorageMB{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DeviceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DeviceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native → Flutter: Device state change callbacks.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class DeviceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DeviceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceApiPigeonCodec()
    }
  }
  /** Called when thermal state changes. */
  fun onThermalStateChanged(thermalStateArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.babymomo.DeviceFlutterApi.onThermalStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(thermalStateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DeviceApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when battery state changes significantly. */
  fun onBatteryStateChanged(levelArg: Double, isChargingArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.babymomo.DeviceFlutterApi.onBatteryStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(levelArg, isChargingArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DeviceApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
