// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.momoai.babymomo.pigeon.inference

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object InferenceApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Model loading request sent from Flutter to native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeModelRequest (
  val modelPath: String,
  val contextLength: Long,
  val threadCount: Long,
  val useGPU: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeModelRequest {
      val modelPath = pigeonVar_list[0] as String
      val contextLength = pigeonVar_list[1] as Long
      val threadCount = pigeonVar_list[2] as Long
      val useGPU = pigeonVar_list[3] as Boolean
      return NativeModelRequest(modelPath, contextLength, threadCount, useGPU)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modelPath,
      contextLength,
      threadCount,
      useGPU,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeModelRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return InferenceApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Inference request sent from Flutter to native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeInferenceRequest (
  val requestId: String,
  val prompt: String,
  val systemPrompt: String? = null,
  val temperature: Double,
  val topP: Double,
  val maxTokens: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeInferenceRequest {
      val requestId = pigeonVar_list[0] as String
      val prompt = pigeonVar_list[1] as String
      val systemPrompt = pigeonVar_list[2] as String?
      val temperature = pigeonVar_list[3] as Double
      val topP = pigeonVar_list[4] as Double
      val maxTokens = pigeonVar_list[5] as Long
      return NativeInferenceRequest(requestId, prompt, systemPrompt, temperature, topP, maxTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      prompt,
      systemPrompt,
      temperature,
      topP,
      maxTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeInferenceRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return InferenceApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Model info returned from native.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeModelInfo (
  val modelPath: String,
  val parameterCount: Long,
  val contextLength: Long,
  val quantization: String,
  val isLoaded: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeModelInfo {
      val modelPath = pigeonVar_list[0] as String
      val parameterCount = pigeonVar_list[1] as Long
      val contextLength = pigeonVar_list[2] as Long
      val quantization = pigeonVar_list[3] as String
      val isLoaded = pigeonVar_list[4] as Boolean
      return NativeModelInfo(modelPath, parameterCount, contextLength, quantization, isLoaded)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modelPath,
      parameterCount,
      contextLength,
      quantization,
      isLoaded,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeModelInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return InferenceApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class InferenceApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeModelRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeInferenceRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeModelInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeModelRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeInferenceRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeModelInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter → Native: Inference operations.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface InferenceHostApi {
  /** Load a model into memory. */
  fun loadModel(request: NativeModelRequest, callback: (Result<Boolean>) -> Unit)
  /** Unload the currently loaded model. */
  fun unloadModel(callback: (Result<Unit>) -> Unit)
  /** Start inference (tokens streamed back via [InferenceFlutterApi]). */
  fun startInference(request: NativeInferenceRequest, callback: (Result<Unit>) -> Unit)
  /** Cancel the currently running inference. */
  fun cancelInference(requestId: String, callback: (Result<Unit>) -> Unit)
  /** Get info about the currently loaded model. */
  fun getModelInfo(callback: (Result<NativeModelInfo?>) -> Unit)
  /** Check if a model is currently loaded. */
  fun isModelLoaded(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by InferenceHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      InferenceApiPigeonCodec()
    }
    /** Sets up an instance of `InferenceHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: InferenceHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.InferenceHostApi.loadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeModelRequest
            api.loadModel(requestArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(InferenceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(InferenceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.InferenceHostApi.unloadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unloadModel{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(InferenceApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(InferenceApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.InferenceHostApi.startInference$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeInferenceRequest
            api.startInference(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(InferenceApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(InferenceApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.InferenceHostApi.cancelInference$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            api.cancelInference(requestIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(InferenceApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(InferenceApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.InferenceHostApi.getModelInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getModelInfo{ result: Result<NativeModelInfo?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(InferenceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(InferenceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.babymomo.InferenceHostApi.isModelLoaded$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isModelLoaded{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(InferenceApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(InferenceApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native → Flutter: Token streaming callbacks.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class InferenceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by InferenceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      InferenceApiPigeonCodec()
    }
  }
  /** Called for each generated token. */
  fun onToken(requestIdArg: String, tokenArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.babymomo.InferenceFlutterApi.onToken$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestIdArg, tokenArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(InferenceApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when inference completes. */
  fun onComplete(requestIdArg: String, totalTokensArg: Long, tokensPerSecondArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.babymomo.InferenceFlutterApi.onComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestIdArg, totalTokensArg, tokensPerSecondArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(InferenceApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when inference encounters an error. */
  fun onError(requestIdArg: String, errorMessageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.babymomo.InferenceFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestIdArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(InferenceApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
